### ISSUE TITLE
Please allow setting a userAgent to fetch/parse podcast RSS feeds

### ISSUE THREAD

**Issue by arnab** [krestaino/podcast-xml-parser#1]
Thanks for this library! It looks awesome, especially being able to fetch with pagination, and limiting the amount of data being fetched.

It is a best-practice to set a clear user-agent while fetching podcast RSS feeds: https://podinfra.net/app-developers/user-agents.html.

Looking at the XML fetching code, the `headers` hard-coded inside the library: https://github.com/krestaino/podcast-xml-parser/blob/main/src/xml.ts#L54-L58C41

Please consider allowing users of the library a way to set a user-agent.

**Comment by krestaino** [comment]
Added in [2.1.0](https://github.com/krestaino/podcast-xml-parser/commit/16d14e2812969767ed6867c7462d9183a3fccdf1). See the [README](https://github.com/krestaino/podcast-xml-parser?tab=readme-ov-file#configuration-options) for more info.

**Comment by arnab** [comment]
Excellent! Thank you @krestaino !
