### ISSUE TITLE
`atom:link` should have `rel="self"`

### ISSUE THREAD

**Issue by harshcut** [krestaino/podcast-xml-parser#8]
**Description**

When retrieving the `atom:link` from an RSS feed, the current implementation fails to accurately identify the correct link for the feed URL. The expected behavior is to obtain the `atom:link` element with the attribute `rel="self"`, representing the feed's own URL. However, the current implementation is not consistently achieving this.

https://github.com/krestaino/podcast-xml-parser/blob/15081c2c61818846c01248cde3d8b1f3f04f612b/src/create.ts#L27

**Current Behavior**

I have [this](https://aufgeldreise.podigee.io/feed/mp3) feed URL, which has multiple `atom:link` elements, out of which the first element is of `rel="hub"` which should not be considered as a feed URL. The same hub is present for multiple feeds and causes an error for unique keys in database.

```xml
<!-- https://aufgeldreise.podigee.io/feed/mp3 -->
<atom:link href="https://pubsubhubbub.appspot.com/" rel="hub"/>
<atom:link href="https://aufgeldreise.podigee.io/feed/mp3" rel="self"/>
<atom:link href="https://aufgeldreise.podigee.io/feed/mp3" rel="first"/>
<atom:link href="https://aufgeldreise.podigee.io/feed/mp3?page=1" rel="last"/>
```

**Expected Behavior**

It should only identify and retrieve the `atom:link` element with the attribute `rel="self"` to obtain the feed's URL. If any links with such attribute is not found, then it should mark it as `undefined`.

**Comment by krestaino** [comment]
Closing, see more here: https://github.com/krestaino/podcast-xml-parser/pull/9#issuecomment-2111341967
